// <auto-generated />
using System;
using GMS.Identity.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GMS.Identity.DataAccess.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20230331073756_AddNewTestUsers")]
    partial class AddNewTestUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("GMS.Identity.Core.Domain.Administration.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a24ab827-10a5-47bf-86bd-39adeb89b6c9"),
                            Email = "sash@mail.ru",
                            IsActive = true,
                            PasswordHash = "jYQ/ud6dDjGLUgzoIWqCxLyfKA5XLWujcoT00jjwI/k=",
                            Role = "Administrator",
                            Salt = "YyaqmwHNHJJ7huxnTd/srg==",
                            TelegramUserName = "@sash",
                            UserName = "Sash"
                        },
                        new
                        {
                            Id = new Guid("8699aba2-5ec1-40cf-b186-36ca13c15ea2"),
                            Email = "dan@mail.ru",
                            IsActive = true,
                            PasswordHash = "ZW62oAyOt2cMhTyfyQeV4ex6buOsCo+442ktnp4ry4g=",
                            Role = "Administrator",
                            Salt = "v3kv2EX3EtGm2HjulHm95A==",
                            TelegramUserName = "@dan",
                            UserName = "Dan"
                        },
                        new
                        {
                            Id = new Guid("c35e71b1-01fe-4e96-aa13-35371f792a4f"),
                            Email = "sys@mail.ru",
                            IsActive = true,
                            PasswordHash = "ZW62oAyOt2cMhTyfyQeV4ex6buOsCo+442ktnp4ry4g=",
                            Role = "System",
                            Salt = "v3kv2EX3EtGm2HjulHm95A==",
                            TelegramUserName = "@system",
                            UserName = "System"
                        },
                        new
                        {
                            Id = new Guid("6f35e9ac-2718-4b98-9a39-d3c136217e97"),
                            Email = "user@mail.ru",
                            IsActive = true,
                            PasswordHash = "ZW62oAyOt2cMhTyfyQeV4ex6buOsCo+442ktnp4ry4g=",
                            Role = "User",
                            Salt = "v3kv2EX3EtGm2HjulHm95A==",
                            TelegramUserName = "@user",
                            UserName = "User"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            Email = "joegold@mail.ru",
                            IsActive = true,
                            PasswordHash = "n5zqX3XdybntUcBHO0vdBjRej+QSduTDeFhTRsrOO9k=",
                            Role = "GYMOwner",
                            Salt = "knowPi2QZNuCrHAlMYyt+w==",
                            TelegramUserName = "@joegold",
                            UserName = "Joe"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000002"),
                            Email = "andrey@mail.ru",
                            IsActive = true,
                            PasswordHash = "n5zqX3XdybntUcBHO0vdBjRej+QSduTDeFhTRsrOO9k=",
                            Role = "GYMOwner",
                            Salt = "knowPi2QZNuCrHAlMYyt+w==",
                            TelegramUserName = "@andrey",
                            UserName = "Андрей"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000003"),
                            Email = "gymowner3@mail.ru",
                            IsActive = true,
                            PasswordHash = "n5zqX3XdybntUcBHO0vdBjRej+QSduTDeFhTRsrOO9k=",
                            Role = "GYMOwner",
                            Salt = "knowPi2QZNuCrHAlMYyt+w==",
                            TelegramUserName = "@gymowner3",
                            UserName = "Owner3"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0001-000000000001"),
                            Email = "goldgymadministrator@mail.ru",
                            IsActive = true,
                            PasswordHash = "3681sgmS5A7DvwlIyHOHJqL0aKD60ImMv7ZEIweBTEs=",
                            Role = "Administrator",
                            Salt = "8rPfOLj0A26zoW0rpFVpyA==",
                            TelegramUserName = "@goldgymadministrator",
                            UserName = "GoldGymAdministrator"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0001-000000000002"),
                            Email = "almazadministrator@mail.ru",
                            IsActive = true,
                            PasswordHash = "3681sgmS5A7DvwlIyHOHJqL0aKD60ImMv7ZEIweBTEs=",
                            Role = "Administrator",
                            Salt = "8rPfOLj0A26zoW0rpFVpyA==",
                            TelegramUserName = "@almazadministrator",
                            UserName = "AlmazAdministrator"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0001-000000000003"),
                            Email = "administrator3@mail.ru",
                            IsActive = true,
                            PasswordHash = "3681sgmS5A7DvwlIyHOHJqL0aKD60ImMv7ZEIweBTEs=",
                            Role = "Administrator",
                            Salt = "8rPfOLj0A26zoW0rpFVpyA==",
                            TelegramUserName = "@administrator3",
                            UserName = "Administrator3"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0006-000000000001"),
                            Email = "goldgymmanager@mail.ru",
                            IsActive = true,
                            PasswordHash = "3681sgmS5A7DvwlIyHOHJqL0aKD60ImMv7ZEIweBTEs=",
                            Role = "Manager",
                            Salt = "8rPfOLj0A26zoW0rpFVpyA==",
                            TelegramUserName = "@goldgymmanager",
                            UserName = "GoldGymManager"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0006-000000000002"),
                            Email = "almazmanager@mail.ru",
                            IsActive = true,
                            PasswordHash = "3681sgmS5A7DvwlIyHOHJqL0aKD60ImMv7ZEIweBTEs=",
                            Role = "Manager",
                            Salt = "8rPfOLj0A26zoW0rpFVpyA==",
                            TelegramUserName = "@almazmanager",
                            UserName = "AlmazManager"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0006-000000000003"),
                            Email = "manager3@mail.ru",
                            IsActive = true,
                            PasswordHash = "3681sgmS5A7DvwlIyHOHJqL0aKD60ImMv7ZEIweBTEs=",
                            Role = "Manager",
                            Salt = "8rPfOLj0A26zoW0rpFVpyA==",
                            TelegramUserName = "@manager3",
                            UserName = "Manager3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Email = "johngold@mail.ru",
                            IsActive = true,
                            PasswordHash = "n5zqX3XdybntUcBHO0vdBjRej+QSduTDeFhTRsrOO9k=",
                            Role = "User",
                            Salt = "knowPi2QZNuCrHAlMYyt+w==",
                            TelegramUserName = "@johngold",
                            UserName = "John"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Email = "ivanalmaz@mail.ru",
                            IsActive = true,
                            PasswordHash = "n5zqX3XdybntUcBHO0vdBjRej+QSduTDeFhTRsrOO9k=",
                            Role = "User",
                            Salt = "knowPi2QZNuCrHAlMYyt+w==",
                            TelegramUserName = "@ivanalmaz",
                            UserName = "Иван"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Email = "user3@mail.ru",
                            IsActive = true,
                            PasswordHash = "n5zqX3XdybntUcBHO0vdBjRej+QSduTDeFhTRsrOO9k=",
                            Role = "User",
                            Salt = "knowPi2QZNuCrHAlMYyt+w==",
                            TelegramUserName = "@user3",
                            UserName = "User3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
