// <auto-generated />
using System;
using GMS.Identity.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GMS.Identity.DataAccess.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20230123202900_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("GMS.Identity.Core.Domain.Administration.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a24ab827-10a5-47bf-86bd-39adeb89b6c9"),
                            Email = "sash@mail.ru",
                            IsActive = true,
                            PasswordHash = "jYQ/ud6dDjGLUgzoIWqCxLyfKA5XLWujcoT00jjwI/k=",
                            Role = "Administrator",
                            Salt = "YyaqmwHNHJJ7huxnTd/srg==",
                            TelegramUserName = "@sash",
                            UserName = "Sash"
                        },
                        new
                        {
                            Id = new Guid("8699aba2-5ec1-40cf-b186-36ca13c15ea2"),
                            Email = "dan@mail.ru",
                            IsActive = true,
                            PasswordHash = "ZW62oAyOt2cMhTyfyQeV4ex6buOsCo+442ktnp4ry4g=",
                            Role = "Administrator",
                            Salt = "v3kv2EX3EtGm2HjulHm95A==",
                            TelegramUserName = "@dan",
                            UserName = "Dan"
                        },
                        new
                        {
                            Id = new Guid("c35e71b1-01fe-4e96-aa13-35371f792a4f"),
                            Email = "sys@mail.ru",
                            IsActive = true,
                            PasswordHash = "ZW62oAyOt2cMhTyfyQeV4ex6buOsCo+442ktnp4ry4g=",
                            Role = "System",
                            Salt = "v3kv2EX3EtGm2HjulHm95A==",
                            TelegramUserName = "@system",
                            UserName = "System"
                        },
                        new
                        {
                            Id = new Guid("6f35e9ac-2718-4b98-9a39-d3c136217e97"),
                            Email = "user@mail.ru",
                            IsActive = true,
                            PasswordHash = "ZW62oAyOt2cMhTyfyQeV4ex6buOsCo+442ktnp4ry4g=",
                            Role = "User",
                            Salt = "v3kv2EX3EtGm2HjulHm95A==",
                            TelegramUserName = "@user",
                            UserName = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
